#pragma once

#define LAYER_STATE_16BIT

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
// #define ONESHOT_TAP_TOGGLE 2

#define EE_HANDS

#define TAPPING_TERM 200
// #define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_F18
// #define RETRO_TAPPING

// Neutralize left alt, left GUI, right GUI and left Control+Shift
#define MODS_TO_NEUTRALIZE { MOD_BIT(KC_LEFT_ALT), MOD_BIT(KC_LEFT_GUI), MOD_BIT(KC_RIGHT_GUI) }

#define EXTRA_SHORT_COMBOS

#ifdef 0 && RGBLIGHT_ENABLE
#    define RGBLIGHT_EFFECT_BREATHING
// #    define RGBLIGHT_EFFECT_RAINBOW_MOOD
// #    define RGBLIGHT_EFFECT_RAINBOW_SWIRL
// #    define RGBLIGHT_EFFECT_SNAKE
// #    define RGBLIGHT_EFFECT_KNIGHT
#    define RGBLIGHT_EFFECT_STATIC_GRADIENT

#    define RGBLIGHT_HUE_STEP 50
#    define RGBLIGHT_SAT_STEP 50
#    define RGBLIGHT_VAL_STEP 50
#    define RGBLIGHT_LIMIT_VAL 150
#    define RGBLIGHT_SPLIT
#    define RGBLIGHT_SLEEP
#    define SPLIT_LED_STATE_ENABLE
#    define SPLIT_TRANSPORT_MIRROR
#    define SPLIT_MODS_ENABLE
#    define SPLIT_LAYER_STATE_ENABLE
#endif
